name: "Deploy IAC"

on:
  push:
    paths:
      - 'iac/**'
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VERSION: 1.9.8

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./iac/

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./iac/

      - name: Terraform Plan
        run: terraform plan -var="sql_password=${{ secrets.SQL_PASSWORD }}" -out=tfplan
        working-directory: ./iac/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./iac/

      - name: Notify Failure
        if: failure()
        run: echo "Terraform deployment failed for ${{ github.ref_name }}"